### ISSUE TITLE
Manifest suggestions

### ISSUE THREAD

**Issue by AndrewBelt** [mgunyho/Little-Utils#1]
VCV has released a new VCV Library website at https://library.vcvrack.com/, so I'm scanning through plugins to find possible improvements for plugin/module metadata.

The plugin URLs and module tags look great, but module descriptions would be the next improvement here.
https://library.vcvrack.com/LittleUtils

**Comment by mgunyho** [comment]
Thanks for letting me know. The site looks great! I've updated the descriptions in https://github.com/mgunyho/Little-Utils/commit/f9cd3b880a7294bf5871987f5d988f475cbc88a5, should I also update the version number?

**Comment by AndrewBelt** [comment]
Yes, and once you've changed the version number, request an update in the library repo.

**Comment by mgunyho** [comment]
Done.
