### ISSUE TITLE
Will you be porting Little Utils to Rack V2?

### ISSUE THREAD

**Issue by Torinbob** [mgunyho/Little-Utils#3]
Hi

Just to let you know that the Rack V2 beta source has been released if you didn't already.

I find your Little Utils modules indispensable so was wondering if you are planning to port them to V2 - I hope so! :)

cheers,
Steve

**Comment by mgunyho** [comment]
Hi!

I'm glad to hear thar you like the modules! I do plan on porting them to V2, although I'm fairly busy right now so it remains to be seen if I'll be able to do it before the official release. I didn't actually know the beta is out, thanks for letting me know! I'll look into it soon.

**Comment by Torinbob** [comment]
That's great news thanks :)

Looks like porting from 1 > 2 is much quicker and simpler than the port from 0.X > 1 was.

Here's a guide that might help: https://vcvrack.com/manual/Migrate2

**Comment by Torinbob** [comment]
Hi mgunyho,

Are you planning to submit Little Utils to the library anytime soon? I know a lot of users are looking forward to them being generally available in v2.

cheers,
Steve

**Comment by mgunyho** [comment]
Hi!

Sorry for the delay. As said, I have been extremely busy recently, but now I have time during the holidays. Hopefully I can get the v2 port done by the end of the year at the latest.

I just downloaded Rack v2.0.4 and the SDK, but my CPU is too old (it doesn't support some AVX instructions required by Rack v2), so I have to build Rack myself, but let's hope it doesn't cause too much problems.
