### ISSUE TITLE
Teleport really does Teleport! across VST plugin instances!

### ISSUE THREAD

**Issue by Torinbob** [mgunyho/Little-Utils#5]
Hi,

I just got sent the Rack 2 VST plugin this evening and I've been spending the last few hours playing with it.

One thing I wasn't expecting, and I'm not sure if this is a good thing or not because it might be causing some issues (need to experiment more), but Teleport is working across different instances of the VST plugin! I really wasn't expecting that haha.

Best,
Steve

**Comment by Torinbob** [comment]
I've told a few people and the general consensus seems to be that Teleport's ability to Teleport across VST plugin instances is the best thing ever - pure magic haha. Everyone hopes this capability is maintained. Teleport is really living up to its name!

btw the issues I was having turned out to be nothing to do with Teleport.

**Comment by mgunyho** [comment]
Hi!

Thanks for letting me know. As I mentioned also in the forum, this is kind of cool but also a bit unexpected. I will not change the behavior for now, but I would expect that problems can arise later on, for example if in a future version the Rack VST instances are in separate processes for some reason. The safest option is to always have unique names for your teleport inputs across the VST instances, although it is a bit cumbersome.
